version: '3.4'

services:
  php:
    build:
      context: ./api
    image: workspace_php
    restart: always
    volumes:
      - ./api:/srv/api:rw
      - ./api/docker/php/conf.d/custom.dev.ini:/usr/local/etc/php/conf.d/custom.ini

  queue:
    build:
      context: ./api
    image: workspace_php
    depends_on:
      - php
    command: php artisan queue:work redis --tries=3 --delay=300
    restart: always
    volumes:
      - ./api:/srv/api:rw
      - ./api/docker/php/conf.d/custom.dev.ini:/usr/local/etc/php/conf.d/custom.ini

  scheduler:
    container_name: scheduler
    image: workspace_php
    depends_on:
      - php
    command: [ "/bin/sh", "-ec", "while true; do php artisan schedule:run; sleep 60 ; done" ]
    restart: always
    volumes:
      - ./api:/srv/api:rw

  proxy:
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    volumes:
      - ./api/public:/srv/api/public:rw
      - ./proxy/docker/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./proxy/docker/nginx/conf.d/api.prod.conf:/etc/nginx/conf.d/api.conf
      - ./proxy/docker/nginx/conf.d/client.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
      - "80:80"

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    expose:
      - 5432

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    volumes:
      - redis-data:/var/lib/redis

  nuxtjs:
    container_name: nuxtjs
    build:
      context: ./client
    image: workspace_nuxtjs
    restart: always
    expose:
      - 3000

volumes:
  db-data: {}
  redis-data: {}